version: "3"
services:
  web-controller:
    build:
      context: ./web-controller
    environment:
      - IMAGE_MODULE_HOST=http://image-module:5000
      - ANALYTICS_MODULE_HOST=http://analytics-module:8080
    ports:
      - "8100:8080"
    networks:
      - tweetnet
  analytics-module:
    build:
      context: ./analytics-module
    links:
        - elasticsearch
    depends_on:
        - elasticsearch
    ports:
      - "8101:8080"
    networks:
      - tweetnet
  nlp-module:
    build:
      context: ./nlp-module
    command: python main.py
    ports:
      - "8102:5000"
    volumes:
      - .:/python-flask
    networks:
      - tweetnet
  image-module:
    build:
      context: ./image-module
    command: python main.py
    ports:
      - "8103:5000"
    volumes:
      - .:/python-flask
    networks:
      - tweetnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: 
      - IPC_LOCK
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200  
    networks:
      - tweetnet
  es-kibana:
    container_name: es-kibana
    image: docker.elastic.co/kibana/kibana:7.15.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - tweetnet
volumes:
  es-data:
    driver: local
networks:
  tweetnet:
    external: true