version: "3"
services:
  web-controller:
    build:
      context: ./web-controller
    ports:
      - "8100:8080"
  analytics-module:
    build:
      context: ./analytics-module
    ports:
      - "8101:8080"
  nlp-module:
    build:
      context: ./nlp-module
    command: python main.py
    ports:
      - "8102:5000"
    volumes:
      - .:/python-flask
  es-main-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - cluster.initial_master_nodes=es-main-db
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200