version: "3"
services:
  web-controller:
    build:
      context: ./web-controller
    ports:
      - "8100:8080"
  analytics-module:
    build:
      context: ./analytics-module
    ports:
      - "8101:8080"
  app:
    build:
      context: ./nlp-module
    command: python main.py
    ports:
      - "8102:5000"
    volumes:
      - .:/python-flask